#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

[ "$(board_name)" = "netcore,n30-pro" ] || exit 0

board_config_update
ucidef_set_interfaces_lan_wan "lan1 lan2 lan3 lan4" "eth1"
board_config_flush

exit 0
